[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  # Environment variables for Firebase (set these in Netlify dashboard)
  # VITE_FIREBASE_API_KEY = "your-api-key"
  # VITE_FIREBASE_AUTH_DOMAIN = "your-project.firebaseapp.com"
  # VITE_FIREBASE_PROJECT_ID = "your-project-id"
  # VITE_FIREBASE_STORAGE_BUCKET = "your-project.appspot.com"
  # VITE_FIREBASE_MESSAGING_SENDER_ID = "your-sender-id"
  # VITE_FIREBASE_APP_ID = "your-app-id"
  # VITE_FIREBASE_MEASUREMENT_ID = "your-measurement-id"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"