// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcqamevjohuksyyrzekn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jcWFtZXZqb2h1a3N5eXJ6ZWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjc3MjAsImV4cCI6MjA1ODg0MzcyMH0.Pd_MX_Mb0OJNhpYi9aotMVt_YPUCkV1K43nwtGWp-1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);